export const AuthTypes = {
    REGISTER_LOADING :  'REGISTER_LOADING',
    REGISTER_SUCCESS :  'REGISTER_SUCCESS',
    REGISTER_ERROR :  'REGISTER_ERROR',
    
    LOGIN_LOADING :  'LOGIN_LOADING',
    LOGIN_SUCCESS :  'LOGIN_SUCCESS',
    LOGIN_ERROR :  'LOGIN_ERROR',

    LOGOUT_USER: 'LOGOUT_USER',

}

