
export const ContactTypes = {
    CONTACTS_LOADING:'CONTACTS_LOADING',
    CONTACTS_SUCCESS:'CONTACTS_SUCCESS',
    CONTACTS_ERROR:'CONTACTS_ERROR',

    CONNECTION_ERROR:'Could not connect to the server',

    ADD_CONTACT_LOADING:'ADD_CONTACT_LOADING',
    ADD_CONTACT_SUCCESS:'ADD_CONTACT_SUCCESS',
    ADD_CONTACT_ERROR:'ADD_CONTACT_ERROR',

    ADD_CONTACT_CLEAR:'ADD_CONTACT_CLEAR',

    SEARCH_CONTACTS: 'SEARCH_CONTACTS'
}